openapi: 3.0.1
info:
  title: '@jupiterone/graph-linear'
  description: An integration and graph conversion project for Linear
  x-cortex-git:
    github:
      repository: JupiterOne/graph-linear
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-linear'
  x-cortex-service-groups:
    - tier-4
